// Nigerian Banks and Microfinance Banks List
export const NIGERIAN_BANKS = [
  // Commercial Banks
  { code: "044", name: "Access Bank" },
  { code: "063", name: "Access Bank (Diamond)" },
  { code: "023", name: "Citibank Nigeria" },
  { code: "050", name: "Ecobank Nigeria" },
  { code: "070", name: "Fidelity Bank" },
  { code: "011", name: "First Bank of Nigeria" },
  { code: "214", name: "First City Monument Bank (FCMB)" },
  { code: "058", name: "Guaranty Trust Bank (GTBank)" },
  { code: "030", name: "Heritage Bank" },
  { code: "301", name: "Jaiz Bank" },
  { code: "082", name: "Keystone Bank" },
  { code: "076", name: "Polaris Bank (Skye Bank)" },
  { code: "101", name: "Providus Bank" },
  { code: "221", name: "Stanbic IBTC Bank" },
  { code: "068", name: "Standard Chartered Bank" },
  { code: "232", name: "Sterling Bank" },
  { code: "100", name: "Suntrust Bank" },
  { code: "032", name: "Union Bank of Nigeria" },
  { code: "033", name: "United Bank for Africa (UBA)" },
  { code: "215", name: "Unity Bank" },
  { code: "035", name: "Wema Bank" },
  { code: "057", name: "Zenith Bank" },
  
  // Microfinance Banks
  { code: "090267", name: "Kuda Microfinance Bank" },
  { code: "090175", name: "Rubies Microfinance Bank" },
  { code: "090110", name: "VFD Microfinance Bank" },
  { code: "090115", name: "TCF Microfinance Bank" },
  { code: "090097", name: "Ekondo Microfinance Bank" },
  { code: "090270", name: "AB Microfinance Bank" },
  { code: "090171", name: "Mainstreet Microfinance Bank" },
  { code: "090259", name: "Alekun Microfinance Bank" },
  { code: "090260", name: "Above Only Microfinance Bank" },
  { code: "090134", name: "Accion Microfinance Bank" },
  { code: "090188", name: "Baines Credit Microfinance Bank" },
  { code: "090326", name: "Sparkle Microfinance Bank" },
  { code: "090329", name: "Neptune Microfinance Bank" },
  { code: "090281", name: "Mint Microfinance Bank" },
  { code: "090285", name: "Rephidim Microfinance Bank" },
  { code: "090286", name: "Safe Haven Microfinance Bank" },
  { code: "090289", name: "Pillar Microfinance Bank" },
  { code: "090299", name: "Kontagora Microfinance Bank" },
  { code: "090303", name: "Purplemoney Microfinance Bank" },
  { code: "090304", name: "Evangel Microfinance Bank" },
  { code: "090305", name: "Sulsap Microfinance Bank" },
  { code: "090307", name: "Aramoko Microfinance Bank" },
  { code: "090308", name: "Brightway Microfinance Bank" },
  { code: "090310", name: "Edfin Microfinance Bank" },
  { code: "090315", name: "U & C Microfinance Bank" },
  { code: "090317", name: "Patrickgold Microfinance Bank" },
  { code: "090322", name: "Renmoney Microfinance Bank" },
  { code: "090324", name: "Ikire Microfinance Bank" },
  { code: "090325", name: "Sparkle Microfinance Bank" },
  { code: "090327", name: "Trust Microfinance Bank" },
  { code: "090328", name: "Eyowo Microfinance Bank" },
  { code: "090331", name: "Unaab Microfinance Bank" },
  { code: "090332", name: "Evergreen Microfinance Bank" },
  { code: "090333", name: "Oche Microfinance Bank" },
  { code: "090336", name: "Bipc Microfinance Bank" },
  { code: "090360", name: "Cashconnect Microfinance Bank" },
  { code: "090363", name: "Headway Microfinance Bank" },
  { code: "090365", name: "Corestep Microfinance Bank" },
  { code: "090369", name: "Seedvest Microfinance Bank" },
  { code: "090370", name: "Ilisan Microfinance Bank" },
  { code: "090371", name: "Agosasa Microfinance Bank" },
  { code: "090373", name: "Think Finance Microfinance Bank" },
  { code: "090374", name: "Trident Microfinance Bank" },
  { code: "090376", name: "Kredi Money Microfinance Bank" },
  { code: "090377", name: "Isaleoyo Microfinance Bank" },
  { code: "090378", name: "New Golden Pastures Microfinance Bank" },
  { code: "090383", name: "Manny Microfinance Bank" },
  { code: "090385", name: "GTI Microfinance Bank" },
  { code: "090386", name: "Interland Microfinance Bank" },
  { code: "090389", name: "EK-Reliable Microfinance Bank" },
  { code: "090391", name: "Davodani Microfinance Bank" },
  { code: "090393", name: "Bridgeway Microfinance Bank" },
  { code: "090394", name: "Amju Unique Microfinance Bank" },
  { code: "090395", name: "Borgu Microfinance Bank" },
  { code: "090396", name: "Oscotech Microfinance Bank" },
  { code: "090399", name: "Ndiorah Microfinance Bank" },
  { code: "090400", name: "Finca Microfinance Bank" },
  { code: "090405", name: "Moniepoint Microfinance Bank" },
  { code: "090409", name: "Flourish Microfinance Bank" },
  { code: "090410", name: "Girei Microfinance Bank" },
  { code: "090411", name: "Finex Microfinance Bank" },
  { code: "090416", name: "Nuture Microfinance Bank" },
  { code: "090435", name: "Fairmoney Microfinance Bank" },
  { code: "090440", name: "Esan Microfinance Bank" },
  { code: "090448", name: "Moyofade Microfinance Bank" },
  { code: "090471", name: "Auchi Microfinance Bank" },
  { code: "090479", name: "Polyunwana Microfinance Bank" },
  { code: "090529", name: "Mint Finex Microfinance Bank" },
  { code: "090530", name: "Lagos Building Investment Company Microfinance Bank" },
  { code: "090531", name: "Aku Microfinance Bank" },
  { code: "090543", name: "Solid Allianze Microfinance Bank" },
  { code: "090561", name: "Hackman Microfinance Bank" },
  { code: "090617", name: "Fbnquest Merchant Bank" },
  
  // Digital Banks & Payment Service Banks
  { code: "120001", name: "9mobile 9Payment Service Bank" },
  { code: "120002", name: "Globus Bank" },
  { code: "120003", name: "Smartcash Payment Service Bank" },
  { code: "120004", name: "Moneybox" },
  { code: "100004", name: "Opay" },
  { code: "100033", name: "Palmpay" },
];

export default NIGERIAN_BANKS;
