// Combined Service Worker for PWA + Firebase Messaging
// This file will be processed by vite-plugin-pwa with injectManifest strategy

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Cache API requests with network-first strategy
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 5, // 5 minutes
      }),
    ],
    networkTimeoutSeconds: 10,
  })
);

// Import Firebase Messaging
// Note: Update the Firebase version and config as needed
// @ts-ignore - Firebase scripts are loaded via importScripts
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
// @ts-ignore
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');

// Firebase configuration
// IMPORTANT: Replace these with your actual Firebase config values
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_SENDER_ID",
  appId: "YOUR_APP_ID"
};

// Initialize Firebase
// @ts-ignore - Firebase is loaded via importScripts
declare const firebase: any;

try {
  firebase.initializeApp(firebaseConfig);
  console.log("Service Worker: Firebase App Initialized");

  // Retrieve an instance of Firebase Messaging
  const messaging = firebase.messaging();
  console.log("Service Worker: Firebase Messaging Initialized");

  // Handle background messages
  messaging.onBackgroundMessage((payload: any) => {
    console.log('[sw.js] Received background message ', payload);

    const notificationTitle = payload.notification?.title || 'VitaNips Notification';
    const notificationOptions: NotificationOptions = {
      body: payload.notification?.body || 'You have a new update.',
      icon: payload.notification?.icon || '/logo.png',
      badge: '/logo.png',
      data: payload.data || {}
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
  });

  // Handle notification clicks
  self.addEventListener('notificationclick', (event: NotificationEvent) => {
    console.log('[sw.js] Notification click received.', event.notification.data);

    event.notification.close();

    const urlToOpen = event.notification.data?.url;

    if (urlToOpen) {
      event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
          // Check if there's already a window open with the target URL
          for (const client of clientList) {
            if (client.url === urlToOpen && 'focus' in client) {
              return (client as WindowClient).focus();
            }
          }
          // If not, open a new window
          if (self.clients.openWindow) {
            return self.clients.openWindow(urlToOpen);
          }
        })
      );
    } else {
      // Default: focus or open the app
      event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
          const existingClient = clientList.find(
            (client) => client.url === '/' && 'focus' in client
          );
          if (existingClient) {
            return (existingClient as WindowClient).focus();
          } else if (self.clients.openWindow) {
            return self.clients.openWindow('/');
          }
        })
      );
    }
  });

} catch (error) {
  console.error("Error initializing Firebase in Service Worker:", error);
}

